-- CREATE NEW CUSTOMER REPORTS TABLE:
create table SCOPS_CUSTOMER_REPORTS
(
    SAP_CUSTOMER_ID           VARCHAR2(10) not null,
    SAP_SALES_ORG_CD          VARCHAR2(4) not  null,
    SERVICE_MODEL             VARCHAR2(15) default 'NONE' not null,
    SCRIPT_ID                 NUMBER(11) not null,
    primary key (SAP_CUSTOMER_ID, SAP_SALES_ORG_CD, SERVICE_MODEL, SCRIPT_ID)
);


-- Populate Table with scripts for stepOneing
INSERT INTO SCOPS_CUSTOMER_REPORTS(SAP_CUSTOMER_ID, SAP_SALES_ORG_CD,SERVICE_MODEL, SCRIPT_ID)
VALUES ('0040013476','U001','SMI',421);

INSERT INTO SCOPS_CUSTOMER_REPORTS(SAP_CUSTOMER_ID, SAP_SALES_ORG_CD,SERVICE_MODEL, SCRIPT_ID)
VALUES ('0040013476','U001','SMI',141);

INSERT INTO SCOPS_CUSTOMER_REPORTS(SAP_CUSTOMER_ID, SAP_SALES_ORG_CD,SERVICE_MODEL, SCRIPT_ID)
VALUES ('0040013476','U001','SMI',61);

INSERT INTO SCOPS_CUSTOMER_REPORTS(SAP_CUSTOMER_ID, SAP_SALES_ORG_CD,SERVICE_MODEL, SCRIPT_ID)
VALUES ('0040013476','U001','SMI',261);

INSERT INTO SCOPS_CUSTOMER_REPORTS(SAP_CUSTOMER_ID, SAP_SALES_ORG_CD,SERVICE_MODEL, SCRIPT_ID)
VALUES ('0040013476','U001','SMI',341);

INSERT INTO SCOPS_CUSTOMER_REPORTS(SAP_CUSTOMER_ID, SAP_SALES_ORG_CD,SERVICE_MODEL, SCRIPT_ID)
VALUES ('0040013476','U001','SMI',241);

INSERT INTO QR_SCRIPT_ACTION_DESTINATIONS (SCRIPT_ID, ACTION_TYPE, DESTINATION)
VALUES (141, 'EMAIL_OUTPUT','greg.witt@avnet.com');

INSERT INTO QR_SCRIPT_ACTION_DESTINATIONS (SCRIPT_ID, ACTION_TYPE, DESTINATION)
VALUES (421, 'EMAIL_OUTPUT','greg.witt@avnet.com');

INSERT INTO QR_SCRIPT_ACTION_DESTINATIONS (SCRIPT_ID, ACTION_TYPE, DESTINATION)
VALUES (61, 'EMAIL_OUTPUT','greg.witt@avnet.com');